language: r
warnings_are_errors: false
r:
  - release
cache:
  - packages
  - ccache
r_packages:
  - covr
after_success:
  - Rscript -e 'library(covr); codecov()'

addons:
  apt:
    sources: ['ubuntu-toolchain-r-test']
    packages:
      - gcc-8
      - g++-8

env:
  global:
  - MAKEFLAGS="-j 2"
  - COMPILER=g++-8
  - CC=gcc-8
  - CXX=g++-8

before_install:
  - sudo apt-get install pkg-config
  - sudo apt-get install unzip
  # - sudo apt-get install libnoise-dev libnoise0
  - sudo apt-get install libgsl-dev
  - sudo apt-get install libtool libtool-bin
  - mkdir -p ~/.R && touch ~/.R/Makevars
  - VER=-8
  - echo "CC=gcc$(VER)"        >> ~/.R/Makevars
  - echo "CXX=g++$(VER)"       >> ~/.R/Makevars
  - echo "CXX1X=g++$(VER)"     >> ~/.R/Makevars
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-8 60 --slave /usr/bin/g++ g++ /usr/bin/g++-8
  # move to home and clone and install libnoise
  - R -q -e 'install.packages("devtools")'
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq

# install: 
  # - chmod +x install_libnoise.sh
  # - sudo ./install_libnoise.sh
  
script:
  - cd src/ann-lib-linux/
  - make
  - cd ..
  # making libnoise in inst
  - cd ../inst/
  - unzip libnoisesrc-1.0.0.zip
  - cd noise/
  - CXXFLAGS='-O3 -fomit-frame-pointer' make CC=gcc-8
  - cd lib
  - sudo ldconfig
  - ln -s libnoise.so.0.3 libnoise.so
  - cd ~/noisewalker
  - Rscript -e 'devtools::check(vignettes = FALSE)'

# safelist
branches:
  only:
  - master
  - develop
