---
title: "Autocorrelation in Perlin Noise"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Autocorrelation in Perlin Noise}
  %\VignetteEncoding{UTF-8}
  %\VignetteEngine{knitr::rmarkdown}
editor_options: 
  chunk_output_type: console
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
# prepare parameter combinations
library(noisewalker)
library(data.table)
library(ggplot2)

# get data.table of parameter combinations
data <- CJ(nOctaves = seq(8), 
           frequency = seq(1, 8, 0.1), 
           increment = 0.01,#c(0.001, seq(10) / 10), 
           repl = seq(100))
```

```{r}
# get vector of values
data[, values := mapply(function(a, b, c) {
 noisewalker::get_values_1d(a, b, c, 1000) 
}, a = nOctaves, b = frequency, c = increment,
SIMPLIFY = FALSE)]
```

```{r}
# small function for acf
get_acf_vals <- function(z, ...) {
  as.vector(stats::acf(z, ..., plot = FALSE)$acf)
}

# small fun for acf range below 0.2
get_acf_range <- function(z) {
  acfr <- which(z < 0.2)[1]
  if (is.na(acfr)){
    acfr <- Inf
  }
  return(acfr)
}
```

```{r}
# get acf of values
data[, acf := lapply(values, get_acf_vals)]

data[, acf_range := unlist(lapply(acf, get_acf_range)) * increment]

# group by octaves, freq, and increment
data_plot <- data[, .(acf_range = mean(acf_range)),
     by = list(nOctaves, frequency)]
```

```{r}
# plot acf_range cubes
ggplot(data)+
  geom_line(aes(frequency, acf_range,
                col = nOctaves,
                group = repl),
                alpha = 0.1,
            show.legend = F)+
  scale_colour_gradient(low = "blue", high = "red")+
  facet_grid(~nOctaves, labeller = label_both)+
  theme_test()

ggsave(filename = "figures/figure_acf_range.png")
```

