---
title: "Running Noisewalker"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{run_noisewalker}
  %\VignetteEncoding{UTF-8}
  %\VignetteEngine{knitr::rmarkdown}
editor_options: 
  chunk_output_type: console
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  eval = FALSE,
  comment = "#>"
)
```

```{r}
# prepare parameter combinations
library(noisewalker)
library(data.table)
library(ggplot2)

# get data.table of parameter combinations
data <- CJ(gmax = 1000,
           tmax = 10,
           nOctaves = 2, 
           frequency = seq(0.001, 8, 1),
           ftransfer = seq(0.001, 8, 1),
           srange = 0.5,
           repl = as.character(seq(3)))
```


```{r setup}
library(noisewalker)

# run over generations
invisible(
  Map(function(gmax, tmax, oct, f, ft, srange, rep) {
    noisewalker::run_noisewalker(gmax, tmax, oct, f, ft, srange, rep)
  }, 
  data$gmax, data$tmax, data$nOctaves, data$frequency,
  data$ftransfer, data$srange, data$repl)
)
```

## Population transfer experiment

```{r}
# read data
files <- list.files("data/", pattern = "16", full.names = T)
params <- fread("data/lookup.csv")

# read data
data <- lapply(files, fread)

# link to params
data <- Map(function(df, f, ft, repl) {
  df[, `:=` (f = f, ft = ft, r = repl)]
}, data, params$frequency, params$fTransfer, params$rep)
```

```{r}
data_copy <- data
data_copy <- rbindlist(data)

# get a subset
data_copy <- data_copy[gen %% 20 == 0,]

# plot figure
ggplot(data_copy)+
  geom_pointrange(aes(gen, mass_mean,
                      ymin = mass_mean - mass_sd,
                      ymax = mass_mean + mass_sd,
                      col = gen < 1000,
                group = interaction(f, ft, r)),
                  size = 0.05,
                  show.legend = F)+
  scale_color_brewer(palette = "Dark2")+
  facet_grid(ft ~ f,
             as.table = F,
             labeller = label_both)

ggsave("figures/fig_transfer_2.png", dpi = 300)
```

