
# Analyse mass evolution

## Prep libraries

```{r}
# prepare parameter combinations
library(noisewalker)
library(data.table)
library(ggplot2)
```

## Clear data

```{r eval=FALSE}
system("rm data/*.csv")
```

## Get data from Peregrine

```{r}
# password
this_password <- readLines("data/password")

# init session
s <- ssh::ssh_connect("p284074@peregrine.hpc.rug.nl", passwd = this_password)

# download to data
ssh::scp_download(s,
                  files = "noisewalker/data", 
                  to = ".")
```


## Population transfer experiment

```{r}
# read data
mass_files <- list.files("data/", pattern = "(mass)", full.names = T)
params <- fread("data/lookup.csv")
```

## Body mass evolution

```{r}
# read mass data
mass_data <- lapply(mass_files[[1]], fread)

# get quantiles
mass_data <- lapply(mass_data, function (df) {
  df[, mass := lapply(stringi::stri_split(mass, fixed = ";"), as.numeric)]
})

# summarise
mass_summary <- lapply(mass_data, function(df) {
  mass_table <- Map(function(m, g) {
    dt <- as.data.table(table(round(m, 1)))
    dt$gen <- g
    return(dt)
    }, df$mass, df$gen
  )
  return(rbindlist(mass_table))
})
```

```{r}
# add params
mass_summary <- Map(function(df, f, ft, repl) {
  df[, `:=` (f = f, ft = ft, r = repl)]
}, mass_summary, params$frequency, params$fTransfer, params$rep)
```


```{r}
dm <- rbindlist(mass_summary)
dm <- split(dm, by = c("f", "ft"))

# plot
plots <- lapply(dm, function(d){
  ggplot(d)+
    geom_vline(xintercept = 1000, lwd = 0.2)+
    geom_tile(aes(gen, as.numeric(V1), fill = N),
              show.legend = F)+
    scale_fill_viridis_c(option = "D")+
    facet_grid(~r)+
    coord_cartesian(ylim = c(0, 10))+
    labs(title = sprintf('ancestral f = %s, new f = %s', unique(d$f), 
                         unique(d$ft)),
         y = "mass")
})

wrap_plots(plots)

ggsave("figures/fig_mass_evol_02.png")
```

## Movement evolution

```{r}
# movement files
move_files <- list.files("data", pattern = "(move)", full.names = T)

# read mass data
move_data <- lapply(move_files, fread)

# get quantiles
move_data <- lapply(move_data, function (df) {
  df[, move := lapply(stringi::stri_split(total_move, fixed = ";"), as.numeric)]
})

# summarise
move_summary <- lapply(move_data, function(df) {
  move_table <- Map(function(m, g) {
    dt <- as.data.table(table(round(m, -1)))
    dt$gen <- g
    return(dt)
    }, df$move, df$gen
  )
  return(rbindlist(move_table))
})
```

```{r}
# add params
move_summary <- Map(function(df, f, ft, repl) {
  df[, `:=` (f = f, ft = ft, r = repl)]
}, move_summary, params$frequency, params$fTransfer, params$rep)
```


```{r}
dm <- rbindlist(move_summary)
dm <- split(dm, by = c("f", "ft"))

# plot
plots <- lapply(dm, function(d){
  ggplot(d)+
    geom_vline(xintercept = 1000, lwd = 0.2)+
    geom_tile(aes(gen, as.numeric(V1) / 100, fill = N),
              show.legend = F)+
    scale_fill_viridis_c(option = "D")+
    facet_grid(~r)+
    coord_cartesian(ylim = c(0, 5))+
    labs(title = sprintf('ancestral f = %s, new f = %s', unique(d$f), 
                         unique(d$ft)),
         y = "total move dist")
})

patchwork::wrap_plots(plots)

ggsave("figures/fig_move_evol_02.png")
```