# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Get samples from the Perlin noise landscape.
#'
#' @description Returns a matrix of landscape values.
#'
#' @param landsize The landscape size.
#' @param octaves Number of octaves. May be thought of as small scale 
#' variability. Must be an integer value between 1 and 8. Higher values
#' result in landscapes with more small scale noise.
#' @param frequency Frequency of noise. May be thought of as large scale
#' variability. May be any double value between 1.0 and 16.0. Higher values
#' mean more patchy landscapes.
#' @param increment The distance between samples. Landscape variabiltiy is scale dependent,
#' so sampling distane must be the same when comparing between landscapes.
#' @param clamp The landscape value below which to return 0, useful when landscape has negative values.
getLandscape <- function(landsize, octaves, frequency, increment, clamp) {
    .Call(`_noisewalker_getLandscape`, landsize, octaves, frequency, increment, clamp)
}

#' Runs the noisewalker simulation.
#'
#' @description Run the noisewalker simulation using parameters passed as
#' arguments to the corresponding R function.
#' 
#' @param popsize The population size.
#' @param genmax The maximum number of generations per simulation.
#' @param timesteps The number of timesteps per generation.
#' @param perception The perception range.
#' @param directions The number of points at which agents sense resources,
#' at a fixed distance of \code{perception} units away from them.
#' @param costMove The cost per move; distance moved is assumed constant.
#' @param freqRisk The patchiness of the landscape of costs.
#' @param freqRes Frequency of noise. May be thought of as large scale
#' variability. May be any double value between 1.0 and 16.0. Higher values
#' mean more patchy landscapes.
#' @param landsize The size of the landscape after which movement is wrapped.
#' Actually, the landscape is infinite, and does not have a repeating pattern.
#' @param clamp The threshold value of the landscape below which, the agents
#' sense and receive zero resources. Needed because noise has values -1 to +1.
#' @param random_traits Should traits be initialised -1 to +1 or at 0.
#' @return A dataframe of evolved pop strategy count.
run_noisewalker <- function(popsize, genmax, timesteps, perception, directions, costMove, freqRisk, freqRes, landsize, clamp, random_traits) {
    .Call(`_noisewalker_run_noisewalker`, popsize, genmax, timesteps, perception, directions, costMove, freqRisk, freqRes, landsize, clamp, random_traits)
}

