# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Runs the noisewalker simulation.
#'
#' @description Run the noisewalker simulation using parameters passed as
#' arguments to the corresponding R function.
#' 
#' @param popsize The population size.
#' @param genmax The maximum number of generations per simulation.
#' @param timesteps The number of timesteps per generation.
#' @param perception The perception range.
#' @param directions The number of points at which agents sense resources,
#' at a fixed distance of \code{perception} units away from them.
#' @param costMove The cost per move; distance moved is assumed constant.
#' @param costSensing The cost per sensing event.
#' @param costCompete The cost per neighbour within the perception range.
#' @param nOctaves Number of octaves. May be thought of as small scale 
#' variability. Must be an integer value between 1 and 8. Higher values
#' result in landscapes with more small scale noise.
#' @param frequency Frequency of noise. May be thought of as large scale
#' variability. May be any double value between 1.0 and 16.0. Higher values
#' mean more patchy landscapes.
#' @param landsize The size of the landscape after which movement is wrapped.
#' Actually, the landscape is infinite, and does not have a repeating pattern.
#' @param clamp The threshold value of the landscape below which, the agents
#' sense and receive zero resources. Needed because noise has values -1 to +1.
#' @return A dataframe of evolved pop strategy count.
run_noisewalker <- function(popsize, genmax, timesteps, perception, directions, costMove, costSensing, costCompete, nOctaves, frequency, landsize, clamp) {
    .Call(`_noisewalker_run_noisewalker`, popsize, genmax, timesteps, perception, directions, costMove, costSensing, costCompete, nOctaves, frequency, landsize, clamp)
}

